#!/bin/bash
# update-backlinks.sh — Maintain a "Backlinks" section on every wiki page
# Usage: update-backlinks.sh [wiki_root] [--check] [--quiet]
# Exit: 0 = up to date (or updated), 1 = --check found pages out of date, 2 = error
#
# Obsidian shows backlinks in its own pane, but the markdown files themselves
# carry no record of what points at them. Writing the list into the page makes
# the graph legible anywhere the files are read — including by an LLM that has
# only opened that one page.
#
# The section is delimited by HTML comment markers and is rewritten wholesale,
# so hand-edits elsewhere in the page are never touched.

set -euo pipefail

# shellcheck source-path=SCRIPTDIR
# shellcheck source=_utils.sh
source "$(dirname "${BASH_SOURCE[0]}")/_utils.sh"

BEGIN_MARK="<!-- BACKLINKS:BEGIN — generated by update-backlinks.sh, do not edit -->"
END_MARK="<!-- BACKLINKS:END -->"

CHECK_ONLY=false
QUIET=false
WIKI_ROOT=""

for arg in "$@"; do
    case "$arg" in
        --help|-h)
            echo "Usage: update-backlinks.sh [wiki_root] [--check] [--quiet]"
            echo "Maintain a generated Backlinks section on every wiki page."
            echo "  --check   Report pages that would change; write nothing"
            echo "  --quiet   Only print errors"
            exit 0 ;;
        --check) CHECK_ONLY=true ;;
        --quiet) QUIET=true ;;
        *)
            if [ -z "$WIKI_ROOT" ]; then
                WIKI_ROOT="$arg"
            else
                echo "Unknown option: $arg (use --help for usage)" >&2; exit 1
            fi ;;
    esac
done

if [ -z "$WIKI_ROOT" ]; then
    WIKI_ROOT="$(find_wiki_root)"
    WIKI_ROOT="${WIKI_ROOT:-./wiki}"
fi

if [ ! -d "$WIKI_ROOT" ]; then
    echo "ERROR: Wiki root '$WIKI_ROOT' does not exist" >&2
    exit 2
fi

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

SLUGS="$TMP/slugs.txt"
ALIASES="$TMP/aliases.tsv"
EDGES="$TMP/edges.tsv"     # target_slug \t source_slug
: > "$SLUGS"; : > "$ALIASES"; : > "$EDGES"

while IFS= read -r -d '' file; do
    slug="$(page_slug "$file")"
    echo "$slug" >> "$SLUGS"
    fm_list "$(extract_frontmatter "$file")" aliases | while IFS= read -r alias; do
        [ -n "$alias" ] && printf '%s\t%s\n' "$alias" "$slug" >> "$ALIASES"
    done
done < <(wiki_pages "$WIKI_ROOT")

while IFS= read -r -d '' file; do
    src="$(page_slug "$file")"
    extract_links "$file" | while IFS= read -r target; do
        [ -z "$target" ] && continue
        resolved=""
        if grep -qFx "$target" "$SLUGS"; then
            resolved="$target"
        elif [ -s "$ALIASES" ]; then
            resolved="$(awk -F'\t' -v a="$target" '$1 == a { print $2; exit }' "$ALIASES")"
        fi
        if [ -n "$resolved" ] && [ "$resolved" != "$src" ]; then
            printf '%s\t%s\n' "$resolved" "$src" >> "$EDGES"
        fi
    done
done < <(wiki_pages "$WIKI_ROOT")

CHANGED=0

while IFS= read -r -d '' file; do
    slug="$(page_slug "$file")"

    SECTION="$TMP/section.md"
    {
        echo "$BEGIN_MARK"
        echo ""
        echo "## Backlinks"
        echo ""
        sources="$(awk -F'\t' -v t="$slug" '$1 == t { print $2 }' "$EDGES" | sort -u)"
        if [ -z "$sources" ]; then
            echo "*No pages link here yet.*"
        else
            printf '%s\n' "$sources" | while IFS= read -r src; do
                echo "- [[$src]]"
            done
        fi
        echo ""
        echo "$END_MARK"
    } > "$SECTION"

    NEW="$TMP/new.md"
    if grep -qF "$BEGIN_MARK" "$file"; then
        # Replace the existing block, leaving the rest of the page untouched.
        awk -v begin="$BEGIN_MARK" -v end="$END_MARK" -v sect="$SECTION" '
            index($0, begin) == 1 { inblock = 1; while ((getline line < sect) > 0) print line; close(sect); next }
            index($0, end) == 1 && inblock { inblock = 0; next }
            !inblock { print }
        ' "$file" > "$NEW"
    else
        {
            cat "$file"
            echo ""
            cat "$SECTION"
        } > "$NEW"
    fi

    if cmp -s "$file" "$NEW"; then
        continue
    fi

    CHANGED=$((CHANGED + 1))
    if [ "$CHECK_ONLY" = true ]; then
        echo "OUTDATED: $slug"
    else
        cat "$NEW" > "$file"
        [ "$QUIET" = false ] && echo "UPDATED: $slug"
    fi
done < <(wiki_pages "$WIKI_ROOT")

if [ "$CHECK_ONLY" = true ]; then
    if [ "$CHANGED" -gt 0 ]; then
        echo "$CHANGED page(s) have out-of-date backlinks."
        exit 1
    fi
    echo "OK: All backlink sections are up to date."
    exit 0
fi

if [ "$QUIET" = false ]; then
    echo "Backlinks updated on $CHANGED page(s)."
fi
